using Microsoft.EntityFrameworkCore;

namespace FormatterApi.Models;
public class FormatterApiContext : DbContext
{
    public DbSet<Country> Countries { get; set; }
    public DbSet<Format> Formats { get; set; }
    public DbSet<Field> Fields { get; set; }
    public DbSet<FormatField> FormatFields { get; set; }
    public FormatterApiContext(DbContextOptions<FormatterApiContext> options) : base(options) { }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<Country>()
            .HasData(
                new Country { CountryId = 1, CountryCode = "AUS", CountryName = "Australia"},
                new Country { CountryId = 2, CountryCode = "BDG", CountryName = "Bangladesh"},
                new Country { CountryId = 3, CountryCode = "CHL", CountryName = "Chile"},
                new Country { CountryId = 4, CountryCode = "GRC", CountryName = "Greece"},
                new Country { CountryId = 5, CountryCode = "IND", CountryName = "India" },
                new Country { CountryId = 6, CountryCode = "USA", CountryName = "United States" }
            );

        builder.Entity<Format>()
            .HasData(
                new Format { FormatId = 1, FormatName = "Australia (general, to street address)", FormatPattern = "{:business}\n{addressee}\n{street-number} {street-name}\n{locality}, {state}, {postal-code}", CountryId = 1 },
                new Format { FormatId = 2, FormatName = "Australia (general, to PO Box)", FormatPattern = "{:business}\n{addressee}\n{po-box}\n{locality}, {state}, {postal-code}", CountryId = 1 },
                new Format { FormatId = 3, FormatName = "Australia (general, to Locked Bag)", FormatPattern = "{:business}\n{addressee}\n{locked-bag-number}\n{locality}, {state}, {postal-code}", CountryId = 1 },
                new Format { FormatId = 4, FormatName = "Bangladesh (urban)", FormatPattern = "{addressee}\n{:additional-details}\n{unit}, {building}\n{street-name} {street-number}\n{town}+{postal-code}\n{country}", CountryId = 2 },
                new Format { FormatId = 5, FormatName = "Bangladesh (rural)", FormatPattern = "{addressee}\n{:additional-details}\nVillage: {village}\nP.O.:{post-office}\nThana: {thana-name}\n{country}", CountryId = 2 },
                new Format { FormatId = 6, FormatName = "Chile (multiple municipality city, with unit/apartment number)", FormatPattern = "{addressee}\n{street-name} {number}, {unit}\n{:postal-code} {municipality}\n{region}", CountryId = 3 },
                new Format { FormatId = 7, FormatName = "Chile (multiple municipality city, no unit/apartment number)", FormatPattern = "{addressee}\n{street-name} {number}\n{:postal-code} {municipality}\n{region}", CountryId = 3 },
                new Format { FormatId = 8, FormatName = "Chile (single municipality city, with unit/apartment number)", FormatPattern = "{addressee}\n{street-name} {number}, {unit}\n{neighborhood}\n{region}", CountryId = 3 },
                new Format { FormatId = 9, FormatName = "Chile (single municipality city, no unit/apartment number)", FormatPattern = "{addressee}\n{street-name} {number}\n{neighborhood}\n{region}", CountryId = 3 },
                new Format { FormatId = 10, FormatName = "Chile (rural, with unit/apartment number)", FormatPattern = "{addressee}\n{street-name} {number}, {unit}\n{postal-code} {town}\n{region}", CountryId = 3 },
                new Format { FormatId = 11, FormatName = "Chile (rural, no unit/apartment number)", FormatPattern = "{addressee}\n{street-name} {number}\n{postal-code} {town}\n{region}", CountryId = 3 },
                new Format { FormatId = 12, FormatName = "Chile (rural, no individual house numbers)", FormatPattern = "{addressee}\n{street-name}, {additional-information}\n{postal-code} {town}\n{region}", CountryId = 3 },
                new Format { FormatId = 13, FormatName = "Greece (non-international mail)", FormatPattern = "{addressee}\n{street-address}\n{postal-code}, {town}", CountryId = 4 },
                new Format { FormatId = 14, FormatName = "Greece (international mail)", FormatPattern = "{addressee}\n{street-address}\n{countrycode} {postal-code}, {town}", CountryId = 4 },
                new Format { FormatId = 15, FormatName = "India (general, international)", FormatPattern = "{addressee} {relation} of {relation-name}\n{door-number} {street-number}, {street-name}\nvia {via-name}\n{post-name}\n{taluk-name}\n{locality}\n{city} - {postal-code}\n{district}\n{state}\n{country}", CountryId = 5 },
                new Format { FormatId = 16, FormatName = "India (rural)", FormatPattern = "{addressee}\n{street-number}, {street-name}\n{village}\n{district}\n{postal-code}\n{state}", CountryId = 5 },
                new Format { FormatId = 17, FormatName = "India (urban)", FormatPattern = "{addressee}\n{:occupation}\n{unit}, {building}\n{street-number}, {street-name}\n{locality}\n{postal-code}\n{state}", CountryId = 5 },
                new Format { FormatId = 18, FormatName = "USA (general)", FormatPattern = "{addressee}\n{house-number}, {street-name}, {unit}\n{city}, {state} {zipcode}", CountryId = 6 }
            );

        builder.Entity<Field>()
            .HasData(
                new Field { FieldId = 1, FieldName = "business" },
                new Field { FieldId = 2, FieldName = "addressee" },
                new Field { FieldId = 3, FieldName = "street-number" },
                new Field { FieldId = 4, FieldName = "street-name" },
                new Field { FieldId = 5, FieldName = "locality" },
                new Field { FieldId = 6, FieldName = "state" },
                new Field { FieldId = 7, FieldName = "postal-code" },
                new Field { FieldId = 8, FieldName = "po-box" },
                new Field { FieldId = 9, FieldName = "locked-bag-number" },
                new Field { FieldId = 10, FieldName = "additional-details" },
                new Field { FieldId = 11, FieldName = "unit" },
                new Field { FieldId = 12, FieldName = "building" },
                new Field { FieldId = 13, FieldName = "town" },
                new Field { FieldId = 14, FieldName = "country" },
                new Field { FieldId = 15, FieldName = "village" },
                new Field { FieldId = 16, FieldName = "post-office" },
                new Field { FieldId = 17, FieldName = "thana-name" },
                new Field { FieldId = 18, FieldName = "number" },
                new Field { FieldId = 19, FieldName = "municipality" },
                new Field { FieldId = 20, FieldName = "region" },
                new Field { FieldId = 21, FieldName = "neighborhood" },
                new Field { FieldId = 22, FieldName = "additional-information" },
                new Field { FieldId = 23, FieldName = "countrycode" },
                new Field { FieldId = 24, FieldName = "relation" },
                new Field { FieldId = 25, FieldName = "relation-name" },
                new Field { FieldId = 26, FieldName = "door-number" },
                new Field { FieldId = 27, FieldName = "via-name" },
                new Field { FieldId = 28, FieldName = "post-name" },
                new Field { FieldId = 29, FieldName = "taluk-name" },
                new Field { FieldId = 30, FieldName = "city" },
                new Field { FieldId = 31, FieldName = "district" },
                new Field { FieldId = 32, FieldName = "state" },
                new Field { FieldId = 33, FieldName = "occupation" },
                new Field { FieldId = 34, FieldName = "house-number" },
                new Field { FieldId = 35, FieldName = "zipcode" },
                new Field { FieldId = 36, FieldName = "street-address" }
            );

        builder.Entity<FormatField>()
            .HasData(
                new FormatField { FormatFieldId = 1, FormatId = 1, FieldId = 1 },
                new FormatField { FormatFieldId = 2, FormatId = 1, FieldId = 2 },
                new FormatField { FormatFieldId = 3, FormatId = 1, FieldId = 3 },
                new FormatField { FormatFieldId = 4, FormatId = 1, FieldId = 4 },
                new FormatField { FormatFieldId = 5, FormatId = 1, FieldId = 5 },
                new FormatField { FormatFieldId = 6, FormatId = 1, FieldId = 6 },
                new FormatField { FormatFieldId = 7, FormatId = 1, FieldId = 7 },
                new FormatField { FormatFieldId = 8, FormatId = 2, FieldId = 1 },
                new FormatField { FormatFieldId = 9, FormatId = 2, FieldId = 2 },
                new FormatField { FormatFieldId = 10, FormatId = 2, FieldId = 8 },
                new FormatField { FormatFieldId = 11, FormatId = 2, FieldId = 6 },
                new FormatField { FormatFieldId = 12, FormatId = 2, FieldId = 7 },
                new FormatField { FormatFieldId = 13, FormatId = 3, FieldId = 1 },
                new FormatField { FormatFieldId = 14, FormatId = 3, FieldId = 2 },
                new FormatField { FormatFieldId = 15, FormatId = 3, FieldId = 9 },
                new FormatField { FormatFieldId = 16, FormatId = 3, FieldId = 5 },
                new FormatField { FormatFieldId = 17, FormatId = 3, FieldId = 6 },
                new FormatField { FormatFieldId = 18, FormatId = 3, FieldId = 7 },
                new FormatField { FormatFieldId = 19, FormatId = 4, FieldId = 2 },
                new FormatField { FormatFieldId = 20, FormatId = 4, FieldId = 10 },
                new FormatField { FormatFieldId = 21, FormatId = 4, FieldId = 11 },
                new FormatField { FormatFieldId = 22, FormatId = 4, FieldId = 12 },
                new FormatField { FormatFieldId = 23, FormatId = 4, FieldId = 4 },
                new FormatField { FormatFieldId = 24, FormatId = 4, FieldId = 3 },
                new FormatField { FormatFieldId = 25, FormatId = 4, FieldId = 13 },
                new FormatField { FormatFieldId = 26, FormatId = 4, FieldId = 7 },
                new FormatField { FormatFieldId = 27, FormatId = 4, FieldId = 14 },
                new FormatField { FormatFieldId = 28, FormatId = 5, FieldId = 2 },
                new FormatField { FormatFieldId = 29, FormatId = 5, FieldId = 10 },
                new FormatField { FormatFieldId = 30, FormatId = 5, FieldId = 15 },
                new FormatField { FormatFieldId = 31, FormatId = 5, FieldId = 16 },
                new FormatField { FormatFieldId = 32, FormatId = 5, FieldId = 17 },
                new FormatField { FormatFieldId = 33, FormatId = 5, FieldId = 14 },
                new FormatField { FormatFieldId = 34, FormatId = 6, FieldId = 2 },
                new FormatField { FormatFieldId = 35, FormatId = 6, FieldId = 4 },
                new FormatField { FormatFieldId = 36, FormatId = 6, FieldId = 18 },
                new FormatField { FormatFieldId = 37, FormatId = 6, FieldId = 11 },
                new FormatField { FormatFieldId = 38, FormatId = 6, FieldId = 7 },
                new FormatField { FormatFieldId = 39, FormatId = 6, FieldId = 19 },
                new FormatField { FormatFieldId = 40, FormatId = 6, FieldId = 20 },
                new FormatField { FormatFieldId = 41, FormatId = 7, FieldId = 2 },
                new FormatField { FormatFieldId = 42, FormatId = 7, FieldId = 4 },
                new FormatField { FormatFieldId = 43, FormatId = 7, FieldId = 18 },
                new FormatField { FormatFieldId = 44, FormatId = 7, FieldId = 7 },
                new FormatField { FormatFieldId = 45, FormatId = 7, FieldId = 19 },
                new FormatField { FormatFieldId = 46, FormatId = 7, FieldId = 20 },
                new FormatField { FormatFieldId = 47, FormatId = 8, FieldId = 2 },
                new FormatField { FormatFieldId = 48, FormatId = 8, FieldId = 4 },
                new FormatField { FormatFieldId = 49, FormatId = 8, FieldId = 18 },
                new FormatField { FormatFieldId = 50, FormatId = 8, FieldId = 11 },
                new FormatField { FormatFieldId = 51, FormatId = 8, FieldId = 21 },
                new FormatField { FormatFieldId = 52, FormatId = 8, FieldId = 20 },
                new FormatField { FormatFieldId = 53, FormatId = 9, FieldId = 2 },
                new FormatField { FormatFieldId = 54, FormatId = 9, FieldId = 4 },
                new FormatField { FormatFieldId = 55, FormatId = 9, FieldId = 18 },
                new FormatField { FormatFieldId = 56, FormatId = 9, FieldId = 21 },
                new FormatField { FormatFieldId = 57, FormatId = 9, FieldId = 20 },
                new FormatField { FormatFieldId = 58, FormatId = 10, FieldId = 2 },
                new FormatField { FormatFieldId = 59, FormatId = 10, FieldId = 4 },
                new FormatField { FormatFieldId = 60, FormatId = 10, FieldId = 18 },
                new FormatField { FormatFieldId = 61, FormatId = 10, FieldId = 11 },
                new FormatField { FormatFieldId = 62, FormatId = 10, FieldId = 7 },
                new FormatField { FormatFieldId = 63, FormatId = 10, FieldId = 13 },
                new FormatField { FormatFieldId = 64, FormatId = 10, FieldId = 20 },
                new FormatField { FormatFieldId = 65, FormatId = 11, FieldId = 2 },
                new FormatField { FormatFieldId = 66, FormatId = 11, FieldId = 4 },
                new FormatField { FormatFieldId = 67, FormatId = 11, FieldId = 18 },
                new FormatField { FormatFieldId = 68, FormatId = 11, FieldId = 7 },
                new FormatField { FormatFieldId = 69, FormatId = 11, FieldId = 13 },
                new FormatField { FormatFieldId = 70, FormatId = 11, FieldId = 20 },
                new FormatField { FormatFieldId = 71, FormatId = 12, FieldId = 2 },
                new FormatField { FormatFieldId = 72, FormatId = 12, FieldId = 4 },
                new FormatField { FormatFieldId = 73, FormatId = 12, FieldId = 22 },
                new FormatField { FormatFieldId = 74, FormatId = 12, FieldId = 7 },
                new FormatField { FormatFieldId = 75, FormatId = 12, FieldId = 13 },
                new FormatField { FormatFieldId = 76, FormatId = 12, FieldId = 20 },
                new FormatField { FormatFieldId = 77, FormatId = 13, FieldId = 2 },
                new FormatField { FormatFieldId = 78, FormatId = 13, FieldId = 3 },
                new FormatField { FormatFieldId = 79, FormatId = 13, FieldId = 7 },
                new FormatField { FormatFieldId = 80, FormatId = 13, FieldId = 13 },
                new FormatField { FormatFieldId = 81, FormatId = 14, FieldId = 2 },
                new FormatField { FormatFieldId = 82, FormatId = 14, FieldId = 36 },
                new FormatField { FormatFieldId = 83, FormatId = 14, FieldId = 23 },
                new FormatField { FormatFieldId = 84, FormatId = 14, FieldId = 7 },
                new FormatField { FormatFieldId = 85, FormatId = 14, FieldId = 13 },
                new FormatField { FormatFieldId = 86, FormatId = 15, FieldId = 2 },
                new FormatField { FormatFieldId = 87, FormatId = 15, FieldId = 24 },
                new FormatField { FormatFieldId = 88, FormatId = 15, FieldId = 25 },
                new FormatField { FormatFieldId = 89, FormatId = 15, FieldId = 26 },
                new FormatField { FormatFieldId = 90, FormatId = 15, FieldId = 3 },
                new FormatField { FormatFieldId = 91, FormatId = 15, FieldId = 4 },
                new FormatField { FormatFieldId = 92, FormatId = 15, FieldId = 27 },
                new FormatField { FormatFieldId = 93, FormatId = 15, FieldId = 28 },
                new FormatField { FormatFieldId = 94, FormatId = 15, FieldId = 29 },
                new FormatField { FormatFieldId = 95, FormatId = 15, FieldId = 5 },
                new FormatField { FormatFieldId = 96, FormatId = 15, FieldId = 30 },
                new FormatField { FormatFieldId = 97, FormatId = 15, FieldId = 16 },
                new FormatField { FormatFieldId = 98, FormatId = 15, FieldId = 31 },
                new FormatField { FormatFieldId = 99, FormatId = 15, FieldId = 32 },
                new FormatField { FormatFieldId = 100, FormatId = 15, FieldId = 14 },
                new FormatField { FormatFieldId = 101, FormatId = 16, FieldId = 2 },
                new FormatField { FormatFieldId = 102, FormatId = 16, FieldId = 3 },
                new FormatField { FormatFieldId = 103, FormatId = 16, FieldId = 4 },
                new FormatField { FormatFieldId = 104, FormatId = 16, FieldId = 15 },
                new FormatField { FormatFieldId = 105, FormatId = 16, FieldId = 31 },
                new FormatField { FormatFieldId = 106, FormatId = 16, FieldId = 7 },
                new FormatField { FormatFieldId = 107, FormatId = 16, FieldId = 32 },
                new FormatField { FormatFieldId = 108, FormatId = 17, FieldId = 2 },
                new FormatField { FormatFieldId = 109, FormatId = 17, FieldId = 33 },
                new FormatField { FormatFieldId = 110, FormatId = 17, FieldId = 11 },
                new FormatField { FormatFieldId = 111, FormatId = 17, FieldId = 12 },
                new FormatField { FormatFieldId = 112, FormatId = 17, FieldId = 3 },
                new FormatField { FormatFieldId = 113, FormatId = 17, FieldId = 4 },
                new FormatField { FormatFieldId = 114, FormatId = 17, FieldId = 5 },
                new FormatField { FormatFieldId = 115, FormatId = 17, FieldId = 7 },
                new FormatField { FormatFieldId = 116, FormatId = 17, FieldId = 6 },
                new FormatField { FormatFieldId = 117, FormatId = 18, FieldId = 2 },
                new FormatField { FormatFieldId = 118, FormatId = 18, FieldId = 34 },
                new FormatField { FormatFieldId = 119, FormatId = 18, FieldId = 4 },
                new FormatField { FormatFieldId = 120, FormatId = 18, FieldId = 11 },
                new FormatField { FormatFieldId = 121, FormatId = 18, FieldId = 30 },
                new FormatField { FormatFieldId = 122, FormatId = 18, FieldId = 32 },
                new FormatField { FormatFieldId = 123, FormatId = 18, FieldId = 35 }
            );
    }
}
