// <auto-generated />
using FormatterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormatterApi.Migrations
{
    [DbContext(typeof(FormatterApiContext))]
    [Migration("20230823184814_AddFormatFieldSeedData")]
    partial class AddFormatFieldSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FormatterApi.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CountryCode")
                        .HasColumnType("longtext");

                    b.Property<string>("CountryName")
                        .HasColumnType("longtext");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryCode = "AUS",
                            CountryName = "Australia"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryCode = "BDG",
                            CountryName = "Bangladesh"
                        },
                        new
                        {
                            CountryId = 3,
                            CountryCode = "CHL",
                            CountryName = "Chile"
                        },
                        new
                        {
                            CountryId = 4,
                            CountryCode = "GRC",
                            CountryName = "Greece"
                        },
                        new
                        {
                            CountryId = 5,
                            CountryCode = "IND",
                            CountryName = "India"
                        },
                        new
                        {
                            CountryId = 6,
                            CountryCode = "USA",
                            CountryName = "United States"
                        });
                });

            modelBuilder.Entity("FormatterApi.Models.Field", b =>
                {
                    b.Property<int>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .HasColumnType("longtext");

                    b.HasKey("FieldId");

                    b.ToTable("Fields");

                    b.HasData(
                        new
                        {
                            FieldId = 1,
                            FieldName = "business"
                        },
                        new
                        {
                            FieldId = 2,
                            FieldName = "addressee"
                        },
                        new
                        {
                            FieldId = 3,
                            FieldName = "street-number"
                        },
                        new
                        {
                            FieldId = 4,
                            FieldName = "street-name"
                        },
                        new
                        {
                            FieldId = 5,
                            FieldName = "locality"
                        },
                        new
                        {
                            FieldId = 6,
                            FieldName = "state"
                        },
                        new
                        {
                            FieldId = 7,
                            FieldName = "postal-code"
                        },
                        new
                        {
                            FieldId = 8,
                            FieldName = "po-box"
                        },
                        new
                        {
                            FieldId = 9,
                            FieldName = "locked-bag-number"
                        },
                        new
                        {
                            FieldId = 10,
                            FieldName = "additional-details"
                        },
                        new
                        {
                            FieldId = 11,
                            FieldName = "unit"
                        },
                        new
                        {
                            FieldId = 12,
                            FieldName = "building"
                        },
                        new
                        {
                            FieldId = 13,
                            FieldName = "town"
                        },
                        new
                        {
                            FieldId = 14,
                            FieldName = "country"
                        },
                        new
                        {
                            FieldId = 15,
                            FieldName = "village"
                        },
                        new
                        {
                            FieldId = 16,
                            FieldName = "post-office"
                        },
                        new
                        {
                            FieldId = 17,
                            FieldName = "thana-name"
                        },
                        new
                        {
                            FieldId = 18,
                            FieldName = "number"
                        },
                        new
                        {
                            FieldId = 19,
                            FieldName = "municipality"
                        },
                        new
                        {
                            FieldId = 20,
                            FieldName = "region"
                        },
                        new
                        {
                            FieldId = 21,
                            FieldName = "neighborhood"
                        },
                        new
                        {
                            FieldId = 22,
                            FieldName = "additional-information"
                        },
                        new
                        {
                            FieldId = 23,
                            FieldName = "countrycode"
                        },
                        new
                        {
                            FieldId = 24,
                            FieldName = "relation"
                        },
                        new
                        {
                            FieldId = 25,
                            FieldName = "relation-name"
                        },
                        new
                        {
                            FieldId = 26,
                            FieldName = "door-number"
                        },
                        new
                        {
                            FieldId = 27,
                            FieldName = "via-name"
                        },
                        new
                        {
                            FieldId = 28,
                            FieldName = "post-name"
                        },
                        new
                        {
                            FieldId = 29,
                            FieldName = "taluk-name"
                        },
                        new
                        {
                            FieldId = 30,
                            FieldName = "city"
                        },
                        new
                        {
                            FieldId = 31,
                            FieldName = "district"
                        },
                        new
                        {
                            FieldId = 32,
                            FieldName = "state"
                        },
                        new
                        {
                            FieldId = 33,
                            FieldName = "occupation"
                        },
                        new
                        {
                            FieldId = 34,
                            FieldName = "house-number"
                        },
                        new
                        {
                            FieldId = 35,
                            FieldName = "zipcode"
                        },
                        new
                        {
                            FieldId = 36,
                            FieldName = "street-address"
                        });
                });

            modelBuilder.Entity("FormatterApi.Models.Format", b =>
                {
                    b.Property<int>("FormatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("FormatName")
                        .HasColumnType("longtext");

                    b.Property<string>("FormatPattern")
                        .HasColumnType("longtext");

                    b.HasKey("FormatId");

                    b.HasIndex("CountryId");

                    b.ToTable("Formats");

                    b.HasData(
                        new
                        {
                            FormatId = 1,
                            CountryId = 1,
                            FormatName = "Australia (general, to street address)",
                            FormatPattern = "{:business}\n{addressee}\n{street-number} {street-name}\n{locality}, {state}, {postal-code}"
                        },
                        new
                        {
                            FormatId = 2,
                            CountryId = 1,
                            FormatName = "Australia (general, to PO Box)",
                            FormatPattern = "{:business}\n{addressee}\n{po-box}\n{locality}, {state}, {postal-code}"
                        },
                        new
                        {
                            FormatId = 3,
                            CountryId = 1,
                            FormatName = "Australia (general, to Locked Bag)",
                            FormatPattern = "{:business}\n{addressee}\n{locked-bag-number}\n{locality}, {state}, {postal-code}"
                        },
                        new
                        {
                            FormatId = 4,
                            CountryId = 2,
                            FormatName = "Bangladesh (urban)",
                            FormatPattern = "{addressee}\n{:additional-details}\n{unit}, {building}\n{street-name} {street-number}\n{town}+{postal-code}\n{country}"
                        },
                        new
                        {
                            FormatId = 5,
                            CountryId = 2,
                            FormatName = "Bangladesh (rural)",
                            FormatPattern = "{addressee}\n{:additional-details}\nVillage: {village}\nP.O.:{post-office}\nThana: {thana-name}\n{country}"
                        },
                        new
                        {
                            FormatId = 6,
                            CountryId = 3,
                            FormatName = "Chile (multiple municipality city, with unit/apartment number)",
                            FormatPattern = "{addressee}\n{street-name} {number}, {unit}\n{:postal-code} {municipality}\n{region}"
                        },
                        new
                        {
                            FormatId = 7,
                            CountryId = 3,
                            FormatName = "Chile (multiple municipality city, no unit/apartment number)",
                            FormatPattern = "{addressee}\n{street-name} {number}\n{:postal-code} {municipality}\n{region}"
                        },
                        new
                        {
                            FormatId = 8,
                            CountryId = 3,
                            FormatName = "Chile (single municipality city, with unit/apartment number)",
                            FormatPattern = "{addressee}\n{street-name} {number}, {unit}\n{neighborhood}\n{region}"
                        },
                        new
                        {
                            FormatId = 9,
                            CountryId = 3,
                            FormatName = "Chile (single municipality city, no unit/apartment number)",
                            FormatPattern = "{addressee}\n{street-name} {number}\n{neighborhood}\n{region}"
                        },
                        new
                        {
                            FormatId = 10,
                            CountryId = 3,
                            FormatName = "Chile (rural, with unit/apartment number)",
                            FormatPattern = "{addressee}\n{street-name} {number}, {unit}\n{postal-code} {town}\n{region}"
                        },
                        new
                        {
                            FormatId = 11,
                            CountryId = 3,
                            FormatName = "Chile (rural, no unit/apartment number)",
                            FormatPattern = "{addressee}\n{street-name} {number}\n{postal-code} {town}\n{region}"
                        },
                        new
                        {
                            FormatId = 12,
                            CountryId = 3,
                            FormatName = "Chile (rural, no individual house numbers)",
                            FormatPattern = "{addressee}\n{street-name}, {additional-information}\n{postal-code} {town}\n{region}"
                        },
                        new
                        {
                            FormatId = 13,
                            CountryId = 4,
                            FormatName = "Greece (non-international mail)",
                            FormatPattern = "{addressee}\n{street-address}\n{postal-code}, {town}"
                        },
                        new
                        {
                            FormatId = 14,
                            CountryId = 4,
                            FormatName = "Greece (international mail)",
                            FormatPattern = "{addressee}\n{street-address}\n{countrycode} {postal-code}, {town}"
                        },
                        new
                        {
                            FormatId = 15,
                            CountryId = 5,
                            FormatName = "India (general, international)",
                            FormatPattern = "{addressee} {relation} of {relation-name}\n{door-number} {street-number}, {street-name}\nvia {via-name}\n{post-name}\n{taluk-name}\n{locality}\n{city} - {postal-code}\n{district}\n{state}\n{country}"
                        },
                        new
                        {
                            FormatId = 16,
                            CountryId = 5,
                            FormatName = "India (rural)",
                            FormatPattern = "{addressee}\n{street-number}, {street-name}\n{village}\n{district}\n{postal-code}\n{state}"
                        },
                        new
                        {
                            FormatId = 17,
                            CountryId = 5,
                            FormatName = "India (urban)",
                            FormatPattern = "{addressee}\n{:occupation}\n{unit}, {building}\n{street-number}, {street-name}\n{locality}\n{postal-code}\n{state}"
                        },
                        new
                        {
                            FormatId = 18,
                            CountryId = 6,
                            FormatName = "USA (general)",
                            FormatPattern = "{addressee}\n{house-number}, {street-name}, {unit}\n{city}, {state} {zipcode}"
                        });
                });

            modelBuilder.Entity("FormatterApi.Models.FormatField", b =>
                {
                    b.Property<int>("FormatFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<int>("FormatId")
                        .HasColumnType("int");

                    b.HasKey("FormatFieldId");

                    b.HasIndex("FieldId");

                    b.HasIndex("FormatId");

                    b.ToTable("FormatFields");

                    b.HasData(
                        new
                        {
                            FormatFieldId = 1,
                            FieldId = 1,
                            FormatId = 1
                        },
                        new
                        {
                            FormatFieldId = 2,
                            FieldId = 2,
                            FormatId = 1
                        },
                        new
                        {
                            FormatFieldId = 3,
                            FieldId = 3,
                            FormatId = 1
                        },
                        new
                        {
                            FormatFieldId = 4,
                            FieldId = 4,
                            FormatId = 1
                        },
                        new
                        {
                            FormatFieldId = 5,
                            FieldId = 5,
                            FormatId = 1
                        },
                        new
                        {
                            FormatFieldId = 6,
                            FieldId = 6,
                            FormatId = 1
                        },
                        new
                        {
                            FormatFieldId = 7,
                            FieldId = 7,
                            FormatId = 1
                        },
                        new
                        {
                            FormatFieldId = 8,
                            FieldId = 1,
                            FormatId = 2
                        },
                        new
                        {
                            FormatFieldId = 9,
                            FieldId = 2,
                            FormatId = 2
                        },
                        new
                        {
                            FormatFieldId = 10,
                            FieldId = 8,
                            FormatId = 2
                        },
                        new
                        {
                            FormatFieldId = 11,
                            FieldId = 6,
                            FormatId = 2
                        },
                        new
                        {
                            FormatFieldId = 12,
                            FieldId = 7,
                            FormatId = 2
                        },
                        new
                        {
                            FormatFieldId = 13,
                            FieldId = 1,
                            FormatId = 3
                        },
                        new
                        {
                            FormatFieldId = 14,
                            FieldId = 2,
                            FormatId = 3
                        },
                        new
                        {
                            FormatFieldId = 15,
                            FieldId = 9,
                            FormatId = 3
                        },
                        new
                        {
                            FormatFieldId = 16,
                            FieldId = 5,
                            FormatId = 3
                        },
                        new
                        {
                            FormatFieldId = 17,
                            FieldId = 6,
                            FormatId = 3
                        },
                        new
                        {
                            FormatFieldId = 18,
                            FieldId = 7,
                            FormatId = 3
                        },
                        new
                        {
                            FormatFieldId = 19,
                            FieldId = 2,
                            FormatId = 4
                        },
                        new
                        {
                            FormatFieldId = 20,
                            FieldId = 10,
                            FormatId = 4
                        },
                        new
                        {
                            FormatFieldId = 21,
                            FieldId = 11,
                            FormatId = 4
                        },
                        new
                        {
                            FormatFieldId = 22,
                            FieldId = 12,
                            FormatId = 4
                        },
                        new
                        {
                            FormatFieldId = 23,
                            FieldId = 4,
                            FormatId = 4
                        },
                        new
                        {
                            FormatFieldId = 24,
                            FieldId = 3,
                            FormatId = 4
                        },
                        new
                        {
                            FormatFieldId = 25,
                            FieldId = 13,
                            FormatId = 4
                        },
                        new
                        {
                            FormatFieldId = 26,
                            FieldId = 7,
                            FormatId = 4
                        },
                        new
                        {
                            FormatFieldId = 27,
                            FieldId = 14,
                            FormatId = 4
                        },
                        new
                        {
                            FormatFieldId = 28,
                            FieldId = 2,
                            FormatId = 5
                        },
                        new
                        {
                            FormatFieldId = 29,
                            FieldId = 10,
                            FormatId = 5
                        },
                        new
                        {
                            FormatFieldId = 30,
                            FieldId = 15,
                            FormatId = 5
                        },
                        new
                        {
                            FormatFieldId = 31,
                            FieldId = 16,
                            FormatId = 5
                        },
                        new
                        {
                            FormatFieldId = 32,
                            FieldId = 17,
                            FormatId = 5
                        },
                        new
                        {
                            FormatFieldId = 33,
                            FieldId = 14,
                            FormatId = 5
                        },
                        new
                        {
                            FormatFieldId = 34,
                            FieldId = 2,
                            FormatId = 6
                        },
                        new
                        {
                            FormatFieldId = 35,
                            FieldId = 4,
                            FormatId = 6
                        },
                        new
                        {
                            FormatFieldId = 36,
                            FieldId = 18,
                            FormatId = 6
                        },
                        new
                        {
                            FormatFieldId = 37,
                            FieldId = 11,
                            FormatId = 6
                        },
                        new
                        {
                            FormatFieldId = 38,
                            FieldId = 7,
                            FormatId = 6
                        },
                        new
                        {
                            FormatFieldId = 39,
                            FieldId = 19,
                            FormatId = 6
                        },
                        new
                        {
                            FormatFieldId = 40,
                            FieldId = 20,
                            FormatId = 6
                        },
                        new
                        {
                            FormatFieldId = 41,
                            FieldId = 2,
                            FormatId = 7
                        },
                        new
                        {
                            FormatFieldId = 42,
                            FieldId = 4,
                            FormatId = 7
                        },
                        new
                        {
                            FormatFieldId = 43,
                            FieldId = 18,
                            FormatId = 7
                        },
                        new
                        {
                            FormatFieldId = 44,
                            FieldId = 7,
                            FormatId = 7
                        },
                        new
                        {
                            FormatFieldId = 45,
                            FieldId = 19,
                            FormatId = 7
                        },
                        new
                        {
                            FormatFieldId = 46,
                            FieldId = 20,
                            FormatId = 7
                        },
                        new
                        {
                            FormatFieldId = 47,
                            FieldId = 2,
                            FormatId = 8
                        },
                        new
                        {
                            FormatFieldId = 48,
                            FieldId = 4,
                            FormatId = 8
                        },
                        new
                        {
                            FormatFieldId = 49,
                            FieldId = 18,
                            FormatId = 8
                        },
                        new
                        {
                            FormatFieldId = 50,
                            FieldId = 11,
                            FormatId = 8
                        },
                        new
                        {
                            FormatFieldId = 51,
                            FieldId = 21,
                            FormatId = 8
                        },
                        new
                        {
                            FormatFieldId = 52,
                            FieldId = 20,
                            FormatId = 8
                        },
                        new
                        {
                            FormatFieldId = 53,
                            FieldId = 2,
                            FormatId = 9
                        },
                        new
                        {
                            FormatFieldId = 54,
                            FieldId = 4,
                            FormatId = 9
                        },
                        new
                        {
                            FormatFieldId = 55,
                            FieldId = 18,
                            FormatId = 9
                        },
                        new
                        {
                            FormatFieldId = 56,
                            FieldId = 21,
                            FormatId = 9
                        },
                        new
                        {
                            FormatFieldId = 57,
                            FieldId = 20,
                            FormatId = 9
                        },
                        new
                        {
                            FormatFieldId = 58,
                            FieldId = 2,
                            FormatId = 10
                        },
                        new
                        {
                            FormatFieldId = 59,
                            FieldId = 4,
                            FormatId = 10
                        },
                        new
                        {
                            FormatFieldId = 60,
                            FieldId = 18,
                            FormatId = 10
                        },
                        new
                        {
                            FormatFieldId = 61,
                            FieldId = 11,
                            FormatId = 10
                        },
                        new
                        {
                            FormatFieldId = 62,
                            FieldId = 7,
                            FormatId = 10
                        },
                        new
                        {
                            FormatFieldId = 63,
                            FieldId = 13,
                            FormatId = 10
                        },
                        new
                        {
                            FormatFieldId = 64,
                            FieldId = 20,
                            FormatId = 10
                        },
                        new
                        {
                            FormatFieldId = 65,
                            FieldId = 2,
                            FormatId = 11
                        },
                        new
                        {
                            FormatFieldId = 66,
                            FieldId = 4,
                            FormatId = 11
                        },
                        new
                        {
                            FormatFieldId = 67,
                            FieldId = 18,
                            FormatId = 11
                        },
                        new
                        {
                            FormatFieldId = 68,
                            FieldId = 7,
                            FormatId = 11
                        },
                        new
                        {
                            FormatFieldId = 69,
                            FieldId = 13,
                            FormatId = 11
                        },
                        new
                        {
                            FormatFieldId = 70,
                            FieldId = 20,
                            FormatId = 11
                        },
                        new
                        {
                            FormatFieldId = 71,
                            FieldId = 2,
                            FormatId = 12
                        },
                        new
                        {
                            FormatFieldId = 72,
                            FieldId = 4,
                            FormatId = 12
                        },
                        new
                        {
                            FormatFieldId = 73,
                            FieldId = 22,
                            FormatId = 12
                        },
                        new
                        {
                            FormatFieldId = 74,
                            FieldId = 7,
                            FormatId = 12
                        },
                        new
                        {
                            FormatFieldId = 75,
                            FieldId = 13,
                            FormatId = 12
                        },
                        new
                        {
                            FormatFieldId = 76,
                            FieldId = 20,
                            FormatId = 12
                        },
                        new
                        {
                            FormatFieldId = 77,
                            FieldId = 2,
                            FormatId = 13
                        },
                        new
                        {
                            FormatFieldId = 78,
                            FieldId = 3,
                            FormatId = 13
                        },
                        new
                        {
                            FormatFieldId = 79,
                            FieldId = 7,
                            FormatId = 13
                        },
                        new
                        {
                            FormatFieldId = 80,
                            FieldId = 13,
                            FormatId = 13
                        },
                        new
                        {
                            FormatFieldId = 81,
                            FieldId = 2,
                            FormatId = 14
                        },
                        new
                        {
                            FormatFieldId = 82,
                            FieldId = 36,
                            FormatId = 14
                        },
                        new
                        {
                            FormatFieldId = 83,
                            FieldId = 23,
                            FormatId = 14
                        },
                        new
                        {
                            FormatFieldId = 84,
                            FieldId = 7,
                            FormatId = 14
                        },
                        new
                        {
                            FormatFieldId = 85,
                            FieldId = 13,
                            FormatId = 14
                        },
                        new
                        {
                            FormatFieldId = 86,
                            FieldId = 2,
                            FormatId = 15
                        },
                        new
                        {
                            FormatFieldId = 87,
                            FieldId = 24,
                            FormatId = 15
                        },
                        new
                        {
                            FormatFieldId = 88,
                            FieldId = 25,
                            FormatId = 15
                        },
                        new
                        {
                            FormatFieldId = 89,
                            FieldId = 26,
                            FormatId = 15
                        },
                        new
                        {
                            FormatFieldId = 90,
                            FieldId = 3,
                            FormatId = 15
                        },
                        new
                        {
                            FormatFieldId = 91,
                            FieldId = 4,
                            FormatId = 15
                        },
                        new
                        {
                            FormatFieldId = 92,
                            FieldId = 27,
                            FormatId = 15
                        },
                        new
                        {
                            FormatFieldId = 93,
                            FieldId = 28,
                            FormatId = 15
                        },
                        new
                        {
                            FormatFieldId = 94,
                            FieldId = 29,
                            FormatId = 15
                        },
                        new
                        {
                            FormatFieldId = 95,
                            FieldId = 5,
                            FormatId = 15
                        },
                        new
                        {
                            FormatFieldId = 96,
                            FieldId = 30,
                            FormatId = 15
                        },
                        new
                        {
                            FormatFieldId = 97,
                            FieldId = 16,
                            FormatId = 15
                        },
                        new
                        {
                            FormatFieldId = 98,
                            FieldId = 31,
                            FormatId = 15
                        },
                        new
                        {
                            FormatFieldId = 99,
                            FieldId = 32,
                            FormatId = 15
                        },
                        new
                        {
                            FormatFieldId = 100,
                            FieldId = 14,
                            FormatId = 15
                        },
                        new
                        {
                            FormatFieldId = 101,
                            FieldId = 2,
                            FormatId = 16
                        },
                        new
                        {
                            FormatFieldId = 102,
                            FieldId = 3,
                            FormatId = 16
                        },
                        new
                        {
                            FormatFieldId = 103,
                            FieldId = 4,
                            FormatId = 16
                        },
                        new
                        {
                            FormatFieldId = 104,
                            FieldId = 15,
                            FormatId = 16
                        },
                        new
                        {
                            FormatFieldId = 105,
                            FieldId = 31,
                            FormatId = 16
                        },
                        new
                        {
                            FormatFieldId = 106,
                            FieldId = 7,
                            FormatId = 16
                        },
                        new
                        {
                            FormatFieldId = 107,
                            FieldId = 32,
                            FormatId = 16
                        },
                        new
                        {
                            FormatFieldId = 108,
                            FieldId = 2,
                            FormatId = 17
                        },
                        new
                        {
                            FormatFieldId = 109,
                            FieldId = 33,
                            FormatId = 17
                        },
                        new
                        {
                            FormatFieldId = 110,
                            FieldId = 11,
                            FormatId = 17
                        },
                        new
                        {
                            FormatFieldId = 111,
                            FieldId = 12,
                            FormatId = 17
                        },
                        new
                        {
                            FormatFieldId = 112,
                            FieldId = 3,
                            FormatId = 17
                        },
                        new
                        {
                            FormatFieldId = 113,
                            FieldId = 4,
                            FormatId = 17
                        },
                        new
                        {
                            FormatFieldId = 114,
                            FieldId = 5,
                            FormatId = 17
                        },
                        new
                        {
                            FormatFieldId = 115,
                            FieldId = 7,
                            FormatId = 17
                        },
                        new
                        {
                            FormatFieldId = 116,
                            FieldId = 6,
                            FormatId = 17
                        },
                        new
                        {
                            FormatFieldId = 117,
                            FieldId = 2,
                            FormatId = 18
                        },
                        new
                        {
                            FormatFieldId = 118,
                            FieldId = 34,
                            FormatId = 18
                        },
                        new
                        {
                            FormatFieldId = 119,
                            FieldId = 4,
                            FormatId = 18
                        },
                        new
                        {
                            FormatFieldId = 120,
                            FieldId = 11,
                            FormatId = 18
                        },
                        new
                        {
                            FormatFieldId = 121,
                            FieldId = 30,
                            FormatId = 18
                        },
                        new
                        {
                            FormatFieldId = 122,
                            FieldId = 32,
                            FormatId = 18
                        },
                        new
                        {
                            FormatFieldId = 123,
                            FieldId = 35,
                            FormatId = 18
                        });
                });

            modelBuilder.Entity("FormatterApi.Models.Format", b =>
                {
                    b.HasOne("FormatterApi.Models.Country", "Country")
                        .WithMany("Formats")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("FormatterApi.Models.FormatField", b =>
                {
                    b.HasOne("FormatterApi.Models.Field", "Field")
                        .WithMany("FormatFields")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormatterApi.Models.Format", "Format")
                        .WithMany("FormatFields")
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Format");
                });

            modelBuilder.Entity("FormatterApi.Models.Country", b =>
                {
                    b.Navigation("Formats");
                });

            modelBuilder.Entity("FormatterApi.Models.Field", b =>
                {
                    b.Navigation("FormatFields");
                });

            modelBuilder.Entity("FormatterApi.Models.Format", b =>
                {
                    b.Navigation("FormatFields");
                });
#pragma warning restore 612, 618
        }
    }
}
